### ISSUE TITLE
搜索地址无效

### ISSUE THREAD

**Issue by jinzhongjia** [eexpress/gnome-shell-weather#2]
目前使用的是gnome42版本，搜索框是正常显示的，但是输入地名后没有任何变化
![image](https://user-images.githubusercontent.com/41784264/175034634-b1797ad8-6274-4047-a77c-fb75277a7827.png)

**Comment by jinzhongjia** [comment]
然后我目前采取的方案是手动查询地址经纬度输入，不知道能否通过gnome的位置信息（笔记本电脑是可以获取经纬度的）自动获取经纬度呢，

**Comment by eexpress** [comment]
回车或者点击右侧的搜索图标（放大镜🔍）

**Comment by jinzhongjia** [comment]
> 回车或者点击右侧的搜索图标（放大镜🔍）

这些都试过了，并没有搜索结果，而且我还尝试全局代理和不代理，均无效果

**Comment by eexpress** [comment]
oops，我过两天试试。这几天医院陪家人。

**Comment by jinzhongjia** [comment]
好的，先陪家人，这个不急

**Comment by eexpress** [comment]
`JS ERROR: TypeError: Soup.SessionAsync is not a constructor`
确定了，某函数被废弃了。多谢提醒。会尽快修正。

**Comment by eexpress** [comment]
才有空，折腾了几小时，才搞清。fedora同时发布2个soup 2.6/3.0版本，ubuntu只带2.6版本。JS加载模块的机制看谁先调用，没有完美兼容方案。先写3.0的方案，更新仓库，但不发布。

**Comment by jinzhongjia** [comment]
> 才有空，折腾了几小时，才搞清。fedora同时发布2个soup 2.6/3.0版本，ubuntu只带2.6版本。JS加载模块的机制看谁先调用，没有完美兼容方案。先写3.0的方案，更新仓库，但不发布。

OK，顺带提一下，我在提这个issue的时候使用的是manjaro

**Comment by eexpress** [comment]
基于arch的，那会有其他问题，记得有人讨论过，说arch以及elementary还是谁谁，某些库想搞另外一套，偏离了gnome上游，具体的问题不记得了。你可以测试下看正常不。下午加了一个i18n的日期显示。
