### ISSUE TITLE
希望增加自动根据当前用户的ip获取经纬度，然后获取天气

### ISSUE THREAD

**Issue by kerojiang** [eexpress/gnome-shell-weather#3]
http://whois.pconline.com.cn/ipAreaCoordJson.jsp
比如这个接口可以直接根据ip返回地址，直接获取到天气，不需要用户去设置

**Comment by eexpress** [comment]
这个之前都想搞。只是ip这事情，一旦做了，就要对国外用户负责。所以不好统一处理啊。😂
